[package]
name = "target_cfg"
version = "0.1.0"
edition = "2021"

# List of excluded files
exclude = [
    "target/*",
    "tests/*",
    ".git/*",
    ".github/*",
    ".gitignore",
    "dep_tag.png",
]


[lib]
proc-macro = true

[dependencies]



[package.metadata.docs.rs]
# Reference : https://stackoverflow.com/questions/61417452/how-to-get-a-feature-requirement-tag-in-the-documentation-generated-by-cargo-do
# Enable unstable features in the documentation
all-features = true
# defines the configuration attribute `docsrs`
rustdoc-args = ["--cfg", "docsrs"]
