[env]
################################
# Default `cfg_boost` aliases #
################################
# cfg_boost-linux = { value = "linux:os", force = false }
# cfg_boost-windows = { value = "windows:os", force = false }
# cfg_boost-macos = { value = "macos:os", force = false }
# cfg_boost-android = { value = "android:os", force = false }
# cfg_boost-ios = { value = "ios:os", force = false }
# cfg_boost-wasm = { value = "wasm:fm", force = false }
# cfg_boost-desktop = { value = "linux:os | windows:os | macos:os", force = false }
# cfg_boost-mobile = { value = "android:os | ios:os", force = false }

#################################################
# Default `cfg_boost` configuration predicates #
#################################################
# cfg_boost_predicate-ar = { value = "target_arch = \"{}\"", force = true } 
# cfg_boost_predicate-tf = { value = "target_feature = "{}"", force = true }
# cfg_boost_predicate-os = { value = "target_os = \"{}\"", force = true } 
# cfg_boost_predicate-fm = { value = "target_family = \"{}\"", force = true } 
# cfg_boost_predicate-ev = { value = "target_env = \"{}\"", force = true } 
# cfg_boost_predicate-ed = { value = "target_endian = \"{}\"", force = true } 
# cfg_boost_predicate-pw = { value = "target_pointer_width = \"{}\"", force = true } 
# cfg_boost_predicate-vn = { value = "target_vendor = \"{}\"", force = true } 
# cfg_boost_predicate-at = { value = "target_has_atomic = \"{}\"", force = true } 
# cfg_boost_predicate-pn = { value = "panic = \"{}\"", force = true }
# cfg_boost_predicate-ft = { value = "feature = \"{}\"", force = true }
