name: ubuntu-latest

on:
  push:
    branches: 
    - main
  pull_request:
    branches:
    - main

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: cargo build --verbose
      
  tests:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Run tests
      run: cargo test --verbose --no-fail-fast --all-targets
      
  toolchain:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Nightly toolchain
      run: rustup toolchain install nightly-x86_64-unknown-linux-gnu

  integration:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Integration tests
      run: bash tests/cfg_boost_tests.sh -i -v    
